import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

export default defineSchema({
  ...authTables,
  sandTypes: defineTable({
    name: v.string(),
    category: v.string(),
    color: v.string(),
    image: v.string(),
    imageStorageId: v.optional(v.id("_storage")),
    price: v.number(),
    grain: v.string(),
    moisture: v.string(),
    density: v.string(),
    origin: v.string(),
    icon: v.string(),
    desc: v.string(),
    uses: v.string(),
  }).index("by_category", ["category"]),
  dealers: defineTable({
    name: v.string(),
    location: v.string(),
    rating: v.number(),
    reviews: v.number(),
    bg: v.string(),
    priceMultiplier: v.number(),
  }),
  trucks: defineTable({
    name: v.string(),
    icon: v.string(),
    capacity: v.string(),
    eta: v.string(),
    baseCost: v.number(),
    perTon: v.number(),
  }),
  orders: defineTable({
    userId: v.id("users"),
    orderNumber: v.string(),
    sandId: v.optional(v.id("sandTypes")),
    dealerId: v.optional(v.id("dealers")),
    truckId: v.optional(v.id("trucks")),
    sellerId: v.optional(v.id("users")),
    transporterId: v.optional(v.id("users")),
    sandName: v.string(),
    dealerName: v.string(),
    truckName: v.string(),
    quantity: v.number(),
    total: v.number(),
    paymentMethod: v.string(),
    status: v.string(),
    address: v.string(),
    pickupLocation: v.optional(v.string()),
    distanceKm: v.optional(v.number()),
    deliveryWindow: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),
  userPrefs: defineTable({
    userId: v.id("users"),
    location: v.string(),
    theme: v.string(),
  }).index("by_user", ["userId"]),
  userProfiles: defineTable({
    userId: v.id("users"),
    name: v.string(),
    email: v.string(),
    phone: v.string(),
  }).index("by_user", ["userId"]),
  sellerApplications: defineTable({
    userId: v.id("users"),
    company: v.string(),
    contactName: v.string(),
    phone: v.string(),
    email: v.string(),
    location: v.string(),
    details: v.string(),
    status: v.string(),
    createdAt: v.number(),
    documents: v.optional(
      v.array(
        v.object({
          label: v.string(),
          storageId: v.id("_storage"),
        }),
      ),
    ),
  }).index("by_user", ["userId"]),
  transportApplications: defineTable({
    userId: v.id("users"),
    company: v.string(),
    contactName: v.string(),
    phone: v.string(),
    email: v.string(),
    vehicleType: v.string(),
    capacity: v.string(),
    baseLocation: v.string(),
    status: v.string(),
    createdAt: v.number(),
    documents: v.optional(
      v.array(
        v.object({
          label: v.string(),
          storageId: v.id("_storage"),
        }),
      ),
    ),
  }).index("by_user", ["userId"]),
  userRoles: defineTable({
    userId: v.id("users"),
    role: v.string(),
  }).index("by_user", ["userId"]),
  sellerProfiles: defineTable({
    userId: v.id("users"),
    company: v.string(),
    location: v.string(),
    phone: v.string(),
    email: v.string(),
  }).index("by_user", ["userId"]),
  transporterProfiles: defineTable({
    userId: v.id("users"),
    company: v.string(),
    baseLocation: v.string(),
    phone: v.string(),
    email: v.string(),
  }).index("by_user", ["userId"]),
  transporterVehicles: defineTable({
    transporterId: v.id("users"),
    label: v.string(),
    capacity: v.string(),
    vehicleType: v.string(),
  }).index("by_transporter", ["transporterId"]),
  sellerSandListings: defineTable({
    sellerId: v.id("users"),
    sandId: v.id("sandTypes"),
    price: v.number(),
    availableTons: v.optional(v.number()),
    cutoffHour: v.optional(v.number()),
    nextRestockAt: v.optional(v.number()),
    createdAt: v.number(),
  })
    .index("by_seller", ["sellerId"])
    .index("by_sand", ["sandId"]),
  orderTrackingUpdates: defineTable({
    orderId: v.id("orders"),
    status: v.string(),
    message: v.string(),
    lat: v.optional(v.number()),
    lng: v.optional(v.number()),
    etaMinutes: v.optional(v.number()),
    createdAt: v.number(),
  }).index("by_order", ["orderId"]),
  quoteRequests: defineTable({
    userId: v.id("users"),
    sandId: v.optional(v.id("sandTypes")),
    sellerId: v.optional(v.id("users")),
    quantity: v.number(),
    deliveryWindow: v.string(),
    address: v.string(),
    notes: v.optional(v.string()),
    status: v.string(),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),
  userLocations: defineTable({
    userId: v.id("users"),
    label: v.string(),
    address: v.string(),
    isDefault: v.boolean(),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),
  adminAuditLogs: defineTable({
    actorId: v.id("users"),
    action: v.string(),
    targetType: v.string(),
    targetId: v.string(),
    status: v.string(),
    reason: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_actor", ["actorId"]),
  reviews: defineTable({
    userId: v.id("users"),
    orderId: v.id("orders"),
    sellerId: v.optional(v.id("users")),
    transporterId: v.optional(v.id("users")),
    sandId: v.optional(v.id("sandTypes")),
    rating: v.number(),
    comment: v.string(),
    createdAt: v.number(),
  })
    .index("by_order", ["orderId"])
    .index("by_seller", ["sellerId"])
    .index("by_transporter", ["transporterId"])
    .index("by_sand", ["sandId"]),
  notifications: defineTable({
    userId: v.id("users"),
    message: v.string(),
    createdAt: v.number(),
    read: v.boolean(),
  }).index("by_user", ["userId"]),
});
